### ISSUE TITLE
Is it possible to have several python versions in a virtualenv?

### ISSUE THREAD

**Issue by jonathan-s** [yyuu/pyenv-virtualenv#143]
Like the question said.

**Comment by blueyed** [comment]
No.

But using pyenv/pyenv-virtualenv you can have multiple virtualenvs "activated".. https://github.com/yyuu/pyenv#choosing-the-python-version

**Comment by blueyed** [comment]
Closing this as hopefully being answered (correctly).

**Comment by jonathan-s** [comment]
Yes, thank you!

On Tuesday, January 19, 2016, Daniel Hahler <notifications@github.com>
wrote:

> Closing this as hopefully being answered (correctly).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yyuu/pyenv-virtualenv/issues/143#issuecomment-172989533>
> .
>


-- 
Sent from Gmail Mobile

**Comment by brechtm** [comment]
This is possible by symlinking another python executable and the lib/pythonx.y folder into an existing virtualenv.

```
ln -s $HOME/.pyenv/versions/3.3.6/bin/python3.3 $HOME/.pyenv/versions/3.5.1/envs/rinoh-test/bin/
ln -s $HOME/.pyenv/versions/3.4.4/bin/python3.4 $HOME/.pyenv/versions/3.5.1/envs/rinoh-test/bin/
ln -s $HOME/.pyenv/versions/3.3.6/lib/python3.3 $HOME/.pyenv/versions/3.5.1/envs/rinoh-test/lib/
ln -s $HOME/.pyenv/versions/3.4.4/lib/python4.4 $HOME/.pyenv/versions/3.5.1/envs/rinoh-test/lib/
```

`rinoh-test` is a Python 3.5 virtualenv.

I have done this to allow Tox within PyCharm to have access to multiple Python versions. Since PyCharm doesn't run tox from a shell, `pyenv local` would not be able to make other Python versions available.

I am not sure whether there are any drawbacks to this approach.

**Comment by brechtm** [comment]
Odd. I cannot get this work when creating a new virtualenv into which I symlink other python executables and lib/pythonx.y folders.

Running tox now fails with:

```
/Users/brechtm/.pyenv/versions/3.3.6/lib/python3.3/distutils/__init__.py:14: UserWarning: The virtualenv distutils package at %s appears to be in the same location as the system distutils?
  "The virtualenv distutils package at %s appears to be in the same location as the system distutils?")
Using base prefix '/Users/brechtm/.pyenv/versions/3.3.6'
Traceback (most recent call last):
  File "/Users/brechtm/.pyenv/versions/3.5.1/envs/tox/lib/python3.5/site-packages/virtualenv.py", line 2332, in <module>
    main()
  File "/Users/brechtm/.pyenv/versions/3.5.1/envs/tox/lib/python3.5/site-packages/virtualenv.py", line 711, in main
    symlink=options.symlink)
  File "/Users/brechtm/.pyenv/versions/3.5.1/envs/tox/lib/python3.5/site-packages/virtualenv.py", line 924, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/Users/brechtm/.pyenv/versions/3.5.1/envs/tox/lib/python3.5/site-packages/virtualenv.py", line 1110, in install_python
    fix_lib64(lib_dir, symlink)
  File "/Users/brechtm/.pyenv/versions/3.5.1/envs/tox/lib/python3.5/site-packages/virtualenv.py", line 1529, in fix_lib64
    if not [p for p in distutils.sysconfig.get_config_vars().values()
  File "/Users/brechtm/.pyenv/versions/3.3.6/lib/python3.3/distutils/__init__.py", line 92, in sysconfig_get_config_vars
    real_vars = old_get_config_vars(*args)
  File "/Users/brechtm/.pyenv/versions/3.3.6/lib/python3.3/distutils/sysconfig.py", line 537, in get_config_vars
    func()
  File "/Users/brechtm/.pyenv/versions/3.3.6/lib/python3.3/distutils/sysconfig.py", line 443, in _init_posix
    filename = get_makefile_filename()
  File "/Users/brechtm/.pyenv/versions/3.3.6/lib/python3.3/distutils/sysconfig.py", line 265, in get_makefile_filename
    lib_dir = get_python_lib(plat_specific=0, standard_lib=1)
  File "/Users/brechtm/.pyenv/versions/3.3.6/lib/python3.3/distutils/__init__.py", line 85, in sysconfig_get_python_lib
    prefix = sys.real_prefix
AttributeError: 'module' object has no attribute 'real_prefix'
Running virtualenv with interpreter /Users/brechtm/.pyenv/versions/tox/bin/python3.3

ERROR: InvocationError: /Users/brechtm/.pyenv/versions/3.5.1/envs/tox/bin/python3.5 -m virtualenv --python /Users/brechtm/.pyenv/versions/tox/bin/python3.3 py33 (see /Users/brechtm/Documents/Code/rinohtype/.tox/py33/log/py33-0.log)
```

I haven't been able to find out what the difference is with the existing virtualenv where this approach does work.

**Comment by brechtm** [comment]
This no longer works with my first (rinoh-test) virtualenv either. I'm not sure what I did exactly, but I did upgrade pyenv and pyenv-virtualenv...

**Comment by brechtm** [comment]
My pyenv setup seems to be messed up. I can't create virtualenvs for Python 3.3(.6) or 3.4(.4) anymore. Trying this spits out the same `sys.real_prefix` error:

```
$ pyenv virtualenv 3.3.6 tox2
Installing pip from https://bootstrap.pypa.io/get-pip.py...
/Users/brechtm/.pyenv/versions/3.3.6/lib/python3.3/distutils/__init__.py:14: UserWarning: The virtualenv distutils package at %s appears to be in the same location as the system distutils?
  "The virtualenv distutils package at %s appears to be in the same location as the system distutils?")
Collecting pip
  Using cached pip-8.1.2-py2.py3-none-any.whl
Collecting setuptools
  Using cached setuptools-24.0.3-py2.py3-none-any.whl
Collecting wheel
  Using cached wheel-0.29.0-py2.py3-none-any.whl
Installing collected packages: pip, setuptools, wheel
Exception:
Traceback (most recent call last):
  File "/var/folders/cm/h_fnh5lx0b5b1b6wvnlc7qlw0000gn/T/tmpq65t1l/pip.zip/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/var/folders/cm/h_fnh5lx0b5b1b6wvnlc7qlw0000gn/T/tmpq65t1l/pip.zip/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/var/folders/cm/h_fnh5lx0b5b1b6wvnlc7qlw0000gn/T/tmpq65t1l/pip.zip/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/var/folders/cm/h_fnh5lx0b5b1b6wvnlc7qlw0000gn/T/tmpq65t1l/pip.zip/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/var/folders/cm/h_fnh5lx0b5b1b6wvnlc7qlw0000gn/T/tmpq65t1l/pip.zip/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/var/folders/cm/h_fnh5lx0b5b1b6wvnlc7qlw0000gn/T/tmpq65t1l/pip.zip/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/var/folders/cm/h_fnh5lx0b5b1b6wvnlc7qlw0000gn/T/tmpq65t1l/pip.zip/pip/locations.py", line 141, in distutils_scheme
    d.parse_config_files()
  File "/Users/brechtm/.pyenv/versions/3.3.6/lib/python3.3/distutils/dist.py", line 360, in parse_config_files
    filenames = self.find_config_files()
  File "/Users/brechtm/.pyenv/versions/3.3.6/lib/python3.3/distutils/__init__.py", line 54, in find_config_files
    found = old_find_config_files(self)
  File "/Users/brechtm/.pyenv/versions/3.3.6/lib/python3.3/distutils/dist.py", line 316, in find_config_files
    check_environ()
  File "/Users/brechtm/.pyenv/versions/3.3.6/lib/python3.3/distutils/util.py", line 185, in check_environ
    os.environ['PLAT'] = get_platform()
  File "/Users/brechtm/.pyenv/versions/3.3.6/lib/python3.3/distutils/util.py", line 103, in get_platform
    distutils.sysconfig.get_config_vars(),
  File "/Users/brechtm/.pyenv/versions/3.3.6/lib/python3.3/distutils/__init__.py", line 92, in sysconfig_get_config_vars
    real_vars = old_get_config_vars(*args)
  File "/Users/brechtm/.pyenv/versions/3.3.6/lib/python3.3/distutils/sysconfig.py", line 537, in get_config_vars
    func()
  File "/Users/brechtm/.pyenv/versions/3.3.6/lib/python3.3/distutils/sysconfig.py", line 443, in _init_posix
    filename = get_makefile_filename()
  File "/Users/brechtm/.pyenv/versions/3.3.6/lib/python3.3/distutils/sysconfig.py", line 265, in get_makefile_filename
    lib_dir = get_python_lib(plat_specific=0, standard_lib=1)
  File "/Users/brechtm/.pyenv/versions/3.3.6/lib/python3.3/distutils/__init__.py", line 85, in sysconfig_get_python_lib
    prefix = sys.real_prefix
AttributeError: 'module' object has no attribute 'real_prefix'
error: failed to install pip via get-pip.py
```

**Comment by brechtm** [comment]
The Python 3.3.6 and 3.4.4 versions installed under `$HOME/.pyenv/versions` were indeed corrupted. I was able to fix my problems by reinstalling these.

I have now **copied** the `lib/pythonx.y` directories into the virtualenv instead of symlinking them, hoping this will prevent corruption of my Python installations.

**Comment by yyuu** [comment]
I am not sure what's going on but sys.real_prefix error reminds me the differences between virtualenv and pyvenv. Installing virtualenv (pip install vierualenv) may help something.

// please be careful I am drunk now ;p

**Comment by brechtm** [comment]
Yes, I also learned about virtualenv and pyvenv during this ordeal. While I have managed to get things working again, I still don't know what caused the corruption.

**Comment by medmunds** [comment]
@brechtm (and anyone else who, like me, ends up here via searching for tox, pyenv, PyCharm, and/or InterpreterNotFound):

> ...to allow Tox within PyCharm to have access to multiple Python versions. Since PyCharm doesn't run tox from a shell, pyenv local would not be able to make other Python versions available.

I was able to get PyCharm's tox runner to find pyenv interpreters by using the [tox-globinterpreter](https://bitbucket.org/ruamel/tox-globinterpreter) plugin:

```bash
pip install tox tox-globinterpreter
tox --scan ~/.pyenv/shims/python?.? ~/.pyenv/shims/pypy*
```

That second line teaches tox (via tox-globinterpreter) to look for python interpreters in pyenv's shim dir. (And then pyenv's shims successfully find the correct interpreters based on local or global pyenv version settings, as you'd expect.)

After that, just run tox normally, from shell or from within PyCharm's integrated runner. No need to create links between virtualenvs. (And in fact, this works even without pyenv's shims in your path, since tox-globinterpreter goes directly to the interpreters you told it about.)

**Comment by brechtm** [comment]
Thanks @medmunds! I recently also learned about [tox-pyenv](https://pypi.python.org/pypi/tox-pyenv), which could also be useful when running tox from PyCharm. My hacky multi-Python virtualenvs is still working fine, so I haven't tried it yet though.

**Comment by medmunds** [comment]
I actually did try tox-pyenv first, which worked great from a shell but failed in PyCharm -- it thought pyenv wasn't installed. (I'm guessing tox-pyenv looks for pyenv along the path, so has the same environment problems with [PyCharm's custom tox runner](https://github.com/JetBrains/intellij-community/blob/master/python/helpers/pycharm/_jb_tox_runner.py) that you ran into originally. But I didn't spend much time trying to debug that combo.)
