### ISSUE TITLE
invalid syntax to run coverage with nosetests

### ISSUE THREAD

**Issue by hoatle** [yyuu/pyenv-virtualenv#146]
the way virtualenv of pyenv prevents me from using coverage + nosetests. Please check out the following steps to reproduce the problem:

```
$ mkdir py-virtualenv
$ cd py-virtualenv/
$ pyenv virtualenv test
New python executable in /home/vagrant/.pyenv/versions/2.7.10/envs/test/bin/python2.7
Also creating executable in /home/vagrant/.pyenv/versions/2.7.10/envs/test/bin/python
Installing setuptools, pip, wheel...done.
Ignoring indexes: https://pypi.python.org/simple
Requirement already satisfied (use --upgrade to upgrade): setuptools in /home/vagrant/.pyenv/versions/2.7.10/envs/test/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): pip in /home/vagrant/.pyenv/versions/2.7.10/envs/test/lib/python2.7/site-packages
$ pyenv activate test
pyenv-virtualenv: deactivate 
pyenv-virtualenv: activate test
pyenv-virtualenv: prompt changing will be removed from future release. configure `export PYENV_VIRTUALENV_DISABLE_PROMPT=1' to simulate the behavior.
(test) $ pip install nosetests
Collecting nosetests
  Could not find a version that satisfies the requirement nosetests (from versions: )
No matching distribution found for nosetests
You are using pip version 7.1.2, however version 8.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(test) $ pip install nose
Collecting nose
  Using cached nose-1.3.7-py2-none-any.whl
Installing collected packages: nose
Successfully installed nose-1.3.7
You are using pip version 7.1.2, however version 8.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(test) $ pip install coverage
Collecting coverage
Installing collected packages: coverage
Successfully installed coverage-4.0.3
You are using pip version 7.1.2, however version 8.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(test) $ nosetests .

----------------------------------------------------------------------
Ran 0 tests in 0.002s

OK
(test) $ coverage run --branch --source=. `which nosetests` -v
Coverage.py warning: No data was collected.
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/test/bin/coverage", line 11, in <module>
    sys.exit(main())
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/test/lib/python2.7/site-packages/coverage/cmdline.py", line 741, in main
    status = CoverageScript().command_line(argv)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/test/lib/python2.7/site-packages/coverage/cmdline.py", line 481, in command_line
    return self.do_run(options, args)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/test/lib/python2.7/site-packages/coverage/cmdline.py", line 620, in do_run
    self.run_python_file(filename, args)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/test/lib/python2.7/site-packages/coverage/execfile.py", line 173, in run_python_file
    code = make_code_from_py(filename)
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/test/lib/python2.7/site-packages/coverage/execfile.py", line 212, in make_code_from_py
    code = compile_unicode(source, filename, "exec")
  File "/home/vagrant/.pyenv/versions/2.7.10/envs/test/lib/python2.7/site-packages/coverage/phystokens.py", line 287, in compile_unicode
    code = compile(source, filename, mode)
  File "/home/vagrant/.pyenv/shims/nosetests", line 3
    [ -n "$PYENV_DEBUG" ] && set -x
                      ^
SyntaxError: invalid syntax
(test) $ 
```

As far as I know, coverage expects nosetests to be python script instead of bash script shimmed by pyenv (as specified from https://github.com/yyuu/pyenv/wiki/Understanding-binstubs#pyenv

I'm not sure if this is the problem from pyenv or coverage.

**Comment by hoatle** [comment]
related: https://bitbucket.org/ned/coveragepy/issues/174/make-it-easier-to-run-python-scripts-under

**Comment by yyuu** [comment]
I'm no longer using `nosetests`. Need more information.

**Comment by hoatle** [comment]
we're going to use Docker for working with different Python versions. We don't need this support any more. Thank you.
