### ISSUE TITLE
pip command not found

### ISSUE THREAD

**Issue by xiazhibin** [yyuu/pyenv-virtualenv#71]
Hi.now that I have created a virtualenv which name env341.
form command 'pyenv virtualenvs' I can see that virtualenv .
but when I want to creat another one virtualenvs by "pyenv virtualenv 2.7.5 evn275".
It fails.Show me that pyenv:pip:command not founde the 'pip' command exists in these Python version:
3.4.1
env341

I am really confuse.
can you tell me how to solve this problem

**Comment by yyuu** [comment]
Probably pip installer failed to install pip. It's a pip issue. Try running `curl https://bootstrap.pypa.io/get-pip.py | python` to fix `pip` installation.

**Comment by joisonwk** [comment]
@yyuu Traceback (most recent call last):
  File "./get-pip.py", line 20061, in <module>
    main()
  File "./get-pip.py", line 194, in main
    bootstrap(tmpdir=tmpdir)
  File "./get-pip.py", line 82, in bootstrap
    import pip
  File "/tmp/tmp9jomde/pip.zip/pip/__init__.py", line 21, in <module>
  File "/tmp/tmp9jomde/pip.zip/pip/_vendor/requests/__init__.py", line 66, in <module>
  File "/tmp/tmp9jomde/pip.zip/pip/_vendor/requests/models.py", line 856
    http_error_msg = u'%s Client Error: %s for url: %s' % (self.status_code, reason, self.url)
