### ISSUE TITLE
Installation of virtual environment fails with Python 3.0.1

### ISSUE THREAD

**Issue by Alp-Phone** [yyuu/pyenv-virtualenv#87]
I tried to install an virtual environment using Python 3.0.1 but the install fails everytime. Pyenv and the plugin are properly installed, as I can install a virtual environment with any other Python versions (i.e. 2.7.10 or 3.3.6).

See the output down below:

```
root@host:/usr/local/pyenv/plugins# pyenv virtualenv 3.0.1 test
Downloading/unpacking virtualenv
  Downloading virtualenv-13.1.0.tar.gz (1.7MB): 1.7MB downloaded
  Running setup.py egg_info for package virtualenv
    warning: no previously-included files matching '*' found under directory 'docs/_templates'
    warning: no previously-included files matching '*' found under directory 'docs/_build'
Installing collected packages: virtualenv
  Running setup.py install for virtualenv
    warning: no previously-included files matching '*' found under directory 'docs/_templates'
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    Installing virtualenv script to /usr/local/pyenv/versions/3.0.1/bin
    Installing virtualenv-3.0 script to /usr/local/pyenv/versions/3.0.1/bin
Successfully installed virtualenv
Cleaning up...
New python executable in /usr/local/pyenv/versions/test/bin/python3.0
Also creating executable in /usr/local/pyenv/versions/test/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /usr/local/pyenv/versions/test/bin/python3.0 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel:
  Traceback (most recent call last):
  File "/usr/local/pyenv/versions/3.0.1/lib/python3.0/site-packages/virtualenv_support/pip-7.1.0-py2.py3-none-any.whl/pip/_vendor/requests/packages/urllib3/_collections.py", line 14, in <module>
ImportError: cannot import name OrderedDict

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/pyenv/versions/3.0.1/lib/python3.0/site-packages/virtualenv_support/pip-7.1.0-py2.py3-none-any.whl/pip/_vendor/requests/packages/urllib3/packages/ordered_dict.py", line 6, in <module>
ImportError: No module named thread

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/pyenv/versions/3.0.1/lib/python3.0/site-packages/virtualenv_support/pip-7.1.0-py2.py3-none-any.whl/pip/__init__.py", line 15, in <module>
  File "/usr/local/pyenv/versions/3.0.1/lib/python3.0/site-packages/virtualenv_support/pip-7.1.0-py2.py3-none-any.whl/pip/vcs/mercurial.py", line 10, in <module>
  File "/usr/local/pyenv/versions/3.0.1/lib/python3.0/site-packages/virtualenv_support/pip-7.1.0-py2.py3-none-any.whl/pip/download.py", line 38, in <module>
  File "/usr/local/pyenv/versions/3.0.1/lib/python3.0/site-packages/virtualenv_support/pip-7.1.0-py2.py3-none-any.whl/pip/_vendor/requests/__init__.py", line 58, in <module>
  File "/usr/local/pyenv/versions/3.0.1/lib/python3.0/site-packages/virtualenv_support/pip-7.1.0-py2.py3-none-any.whl/pip/_vendor/requests/utils.py", line 26, in <module>
  File "/usr/local/pyenv/versions/3.0.1/lib/python3.0/site-packages/virtualenv_support/pip-7.1.0-py2.py3-none-any.whl/pip/_vendor/requests/compat.py", line 7, in <module>
  File "/usr/local/pyenv/versions/3.0.1/lib/python3.0/site-packages/virtualenv_support/pip-7.1.0-py2.py3-none-any.whl/pip/_vendor/requests/packages/__init__.py", line 3, in <module>
  File "/usr/local/pyenv/versions/3.0.1/lib/python3.0/site-packages/virtualenv_support/pip-7.1.0-py2.py3-none-any.whl/pip/_vendor/requests/packages/urllib3/__init__.py", line 10, in <module>
  File "/usr/local/pyenv/versions/3.0.1/lib/python3.0/site-packages/virtualenv_support/pip-7.1.0-py2.py3-none-any.whl/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 38, in <module>
  File "/usr/local/pyenv/versions/3.0.1/lib/python3.0/site-packages/virtualenv_support/pip-7.1.0-py2.py3-none-any.whl/pip/_vendor/requests/packages/urllib3/response.py", line 9, in <module>
  File "/usr/local/pyenv/versions/3.0.1/lib/python3.0/site-packages/virtualenv_support/pip-7.1.0-py2.py3-none-any.whl/pip/_vendor/requests/packages/urllib3/_collections.py", line 16, in <module>
  File "/usr/local/pyenv/versions/3.0.1/lib/python3.0/site-packages/virtualenv_support/pip-7.1.0-py2.py3-none-any.whl/pip/_vendor/requests/packages/urllib3/packages/ordered_dict.py", line 8, in <module>
ImportError: No module named dummy_thread
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/local/pyenv/versions/3.0.1/bin/virtualenv", line 9, in <module>
    load_entry_point('virtualenv==13.1.0', 'console_scripts', 'virtualenv')()
  File "/usr/local/pyenv/versions/3.0.1/lib/python3.0/site-packages/virtualenv.py", line 832, in main
    symlink=options.symlink)
  File "/usr/local/pyenv/versions/3.0.1/lib/python3.0/site-packages/virtualenv.py", line 1004, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/usr/local/pyenv/versions/3.0.1/lib/python3.0/site-packages/virtualenv.py", line 969, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/usr/local/pyenv/versions/3.0.1/lib/python3.0/site-packages/virtualenv.py", line 910, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /usr/local/pyenv/versions/test/bin/python3.0 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 1
Installing pip from https://bootstrap.pypa.io/get-pip.py...
Traceback (most recent call last):
  File "/tmp/tmpRFEaBt/pip.zip/pip/_vendor/requests/packages/urllib3/_collections.py", line 14, in <module>
ImportError: cannot import name OrderedDict

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/tmpRFEaBt/pip.zip/pip/_vendor/requests/packages/urllib3/packages/ordered_dict.py", line 6, in <module>
ImportError: No module named thread

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/pyenv/cache/get-pip.py", line 17767, in <module>
    main()
  File "/usr/local/pyenv/cache/get-pip.py", line 162, in main
    bootstrap(tmpdir=tmpdir)
  File "/usr/local/pyenv/cache/get-pip.py", line 82, in bootstrap
    import pip
  File "/tmp/tmpRFEaBt/pip.zip/pip/__init__.py", line 15, in <module>
  File "/tmp/tmpRFEaBt/pip.zip/pip/vcs/mercurial.py", line 10, in <module>
  File "/tmp/tmpRFEaBt/pip.zip/pip/download.py", line 38, in <module>
  File "/tmp/tmpRFEaBt/pip.zip/pip/_vendor/requests/__init__.py", line 58, in <module>
  File "/tmp/tmpRFEaBt/pip.zip/pip/_vendor/requests/utils.py", line 26, in <module>
  File "/tmp/tmpRFEaBt/pip.zip/pip/_vendor/requests/compat.py", line 7, in <module>
  File "/tmp/tmpRFEaBt/pip.zip/pip/_vendor/requests/packages/__init__.py", line 3, in <module>
  File "/tmp/tmpRFEaBt/pip.zip/pip/_vendor/requests/packages/urllib3/__init__.py", line 10, in <module>
  File "/tmp/tmpRFEaBt/pip.zip/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 38, in <module>
  File "/tmp/tmpRFEaBt/pip.zip/pip/_vendor/requests/packages/urllib3/response.py", line 9, in <module>
  File "/tmp/tmpRFEaBt/pip.zip/pip/_vendor/requests/packages/urllib3/_collections.py", line 16, in <module>
  File "/tmp/tmpRFEaBt/pip.zip/pip/_vendor/requests/packages/urllib3/packages/ordered_dict.py", line 8, in <module>
ImportError: No module named dummy_thread
error: failed to install pip via get-pip.py
```

**Comment by yyuu** [comment]
It seems your Python is way too old and recent version of virtualenv doesn't support the version. You might need to consider downgrading virtualenv version.

**Comment by Alp-Phone** [comment]
This is weird because I was able to install virtual enviroments with Python 2.7.10 and 3.3.6. My system Python (2.6.6) is quite old becuase I use Debian 6.0.10. I am trying to install an up-to-date Python version for some Django applications.

In the documentation for pyenv you state:

"In contrast with pythonbrew and pythonz, pyenv does not...
- Depend on Python itself. pyenv was made from pure shell scripts. There is no bootstrap problem of Python"

This means to me that pyenv isn't relying on the sytem Python to install further python versions. Or do I get something wrong here?

This is my output when installing a virtual enviroment unsing Python 3.3.6:

```
root@bora:/usr/local/pyenv/plugins# pyenv versions
* system (set by /usr/local/pyenv/version)
  2.7.10
  3.0.1
  3.3.6
  test
  test2
  test4
root@bora:/usr/local/pyenv/plugins# python --version
Python 2.6.6
root@bora:/usr/local/pyenv/plugins# pyenv virtualenv 3.3.6 test5
Installing pip from https://bootstrap.pypa.io/get-pip.py...
Collecting pip
  Using cached pip-7.1.0-py2.py3-none-any.whl
Collecting setuptools
  Using cached setuptools-18.0.1-py2.py3-none-any.whl
Collecting wheel
  Using cached wheel-0.24.0-py2.py3-none-any.whl
Installing collected packages: pip, setuptools, wheel
Successfully installed pip-7.1.0 setuptools-18.0.1 wheel-0.24.0
```

**Comment by yyuu** [comment]
The version of system python isn't related. The cause is Python 3.0.1.

**Comment by yyuu** [comment]
This isn't an issue of pyenv-virtilualenv

**Comment by Alp-Phone** [comment]
Ok, so is there a list of Python versions which pyenv-virtualenv supports? How can I find out which Python versions are good to use?

**Comment by yyuu** [comment]
pyenv-virtualenv is just a wrapper of virtualenv. The supported versions are as same as virtualenv itself.
